# Generated by Django 5.2.5 on 2025-08-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LatestPw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("req_id", models.CharField(max_length=63)),
                ("pw", models.CharField(max_length=255)),
                ("as_of", models.DateTimeField()),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("req_id", ""), _negated=True),
                            models.Q(("pw", ""), _negated=True),
                        ),
                        name="lpw_fields_not_blank",
                        violation_error_code="fields_blank",
                        violation_error_message="Fields cannot be blank.",
                    ),
                    models.UniqueConstraint(fields=("req_id",), name="lpw_req_id_uix"),
                ],
            },
        ),
    ]
